- name: Catalogue Service
  hosts: catalogue
  become: yes

  vars:
    mongodb_host: 172.31.17.175

  tasks:
    # ---------------- NodeJS Setup ----------------
    - name: Install NodeJS 18.x repo
      ansible.builtin.shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      args:
        executable: /bin/bash

    - name: Install NodeJS
      ansible.builtin.apt:
        name: nodejs
        state: present
        update_cache: yes

    # ---------------- App User & Directory ----------------
    - name: Create application user
      ansible.builtin.user:
        name: roboshop
        state: present
        create_home: yes

    - name: Remove old app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create app directory
      ansible.builtin.file:
        path: /app
        state: directory
        owner: roboshop
        group: roboshop

    # ---------------- App Code ----------------
    - name: Download catalogue service code
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp/catalogue.zip

    - name: Install unzip
      ansible.builtin.apt:
        name: unzip
        state: present
        update_cache: yes

    - name: Extract catalogue service code
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: Install catalogue service dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app
        creates: /app/node_modules

    # ---------------- Systemd Service ----------------
    - name: Configure systemd file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service
        mode: "0644"

    - name: Reload systemd and start catalogue service
      ansible.builtin.systemd:
        name: catalogue
        daemon_reload: yes
        state: restarted
        enabled: yes

    # ---------------- MongoDB Client ----------------
    - name: copy mongoddb repo file
      ansible.builtin.copy:
        src: mongodb.repo
        dest: /etc/yum.reos.d/mongo.repo
        remote_src: yes
        mode: "0644"
        update_cache: yes

    - name: Install MongoDB client
      ansible.builtin.apt:
        name: mongodb-org-shell
        state: present
        update_cache: yes

    # ---------------- Load Catalogue Data ----------------
    - name: Get categories count
      ansible.builtin.command: >
        mongo --host {{ mongodb_host }} --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
      register: product_count

    - name: Load catalogue data if empty
      ansible.builtin.command: mongo --host {{ mongodb_host }} < schema/catalogue.js
      args:
        chdir: /app
        warn: false
      when: product_count.stdout == "0"
