- name: catalogue service
  hosts: catalogue
  become: yes

  tasks:
    - name: Install NodeJS 18.x repo
      ansible.builtin.shell: |
        curl -fsSL https://deb.nodesource.com/setup_18.x | bash -
      args:
        executable: /bin/bash

    - name: Install NodeJS
      ansible.builtin.apt:
        name: nodejs
        state: present
        update_cache: yes

    - name: Create application user
      ansible.builtin.user:
        name: roboshop
        state: present
        create_home: yes

    - name: Recursively remove app directory
      ansible.builtin.file:
        path: /app
        state: absent

    - name: Create application directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download catalogue service code
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
        dest: /tmp

    - name: Extract catalogue service code
      ansible.builtin.unarchive:
        src: /tmp/catalogue.zip
        dest: /app
        remote_src: yes

    - name: Install catalogue service dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app

    - name: Configure catalogue service systemd file
      ansible.builtin.copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: deamon realod and start
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Start and enable catalogue service
      ansible.builtin.systemd:
        name: catalogue
        enabled: yes
    - name: Add MongoDB 7.0 repository (for Ubuntu Jammy)
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/mongodb-org-7.0.list
        content: "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-7.gpg ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse"
        mode: "0644"

    - name: Install MongoDB shell client
      ansible.builtin.apt:
        name: mongodb-org-shell
        state: present
        update_cache: yes

    - name: get the categories count
      ansible.builtin.command: mongo --host 172.31.17.131 --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
      register: product_count

    - name: load catalogue data
      ansible.builtin.command: mongo --host 172.31.17.131 < /app/schema/catalogue.js
      when: product_count.stdout == "0" # keep double quotes

    - name: start and enable catalogue
      ansible.builtin.service:
        name: catalogue
        state: restarted
        enabled: yes
