- name: Install and configure MongoDB 7.0 on Ubuntu 22.04
  hosts: mongodb
  become: yes

  tasks:
    - name: adding mongodb repo
      ansible.builtin.copy:
        src: mongod.repo
        dest: /etc/yum.repos.d/mongod.repo

    - name: install mongo mongodb-org
      ansible.builtin.yum:
        name: mongodb-org
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Enable and start mongod service
      ansible.builtin.service:
        name: mongod
        state: started
        enabled: yes

    - name: replacing the listener address
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: "127.0.0.1"
        replace: "0.0.0.0"

    - name: restart mongod service
      ansible.builtin.service:
        name: mongod
        state: restarted
