- name: Installing and configuring MongoDB
  hosts: mongodb
  become: yes
  tasks:
    - name: Import MongoDB public GPG key
      ansible.builtin.get_url:
        url: https://www.mongodb.org/static/pgp/server-7.0.asc
        dest: /usr/share/keyrings/mongodb-server-7.0.gpg
        mode: "0644"

    - name: Creating a list file for MongoDB
      ansible.builtin.copy:
        dest: /etc/apt/sources.list.d/mongodb-org-7.0.list
        content: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/7.0 multiverse"
        mode: "0644"

    - name: Updating the apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Installing MongoDB packages
      ansible.builtin.apt:
        name: mongodb-org
        state: present

    - name: Starting MongoDB service
      ansible.builtin.service:
        name: mongod
        state: started
    - name: replacing the listener address
      ansible.builtin.replace:
        path: /etc/mongod.conf
        regexp: "127.0.0.1"
        replace: "0.0.0.0"
    - name: restart mongod service
      ansible.builtin.service:
        name: mongod
        state: restarted
