- name: mysql setup
  hosts: mysql
  become: true

  vars:
    mysql_root_password: "Roboshop@123"

  tasks:
    - name: copying mysql repo file
      ansible.builtin.copy:
        src: mysql.repo
        dest: /etc/yum.repos.d/mysql.repo

    - name: installing mysql server
      ansible.builtin.yum:
        name: mysql-community-server
        state: present

    - name: starting and enabling mysql service
      ansible.builtin.systemd:
        name: mysqld
        enabled: yes
        state: started

    - name: set MySQL root password (for MySQL 8+)
      ansible.builtin.shell: |
        sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ mysql_root_password }}';"
        args:
         creates: /tmp/mysql_root_password_set
