- name: Setup Redis 6 on Amazon Linux 2023
  hosts: redis
  become: yes

  tasks:
    - name: Install Redis 6
      ansible.builtin.dnf:
        name: redis6
        state: present

    - name: Update Redis listen address
      ansible.builtin.replace:
        path: /etc/redis6/redis6.conf
        regexp: '^bind\s+127\.0\.0\.1'
        replace: "bind 0.0.0.0"

    - name: Disable protected mode
      ansible.builtin.replace:
        path: /etc/redis6/redis6.conf
        regexp: '^protected-mode\s+yes'
        replace: "protected-mode no"

    - name: Enable and start Redis service
      ansible.builtin.systemd:
        name: redis6
        state: started
        enabled: yes
