- name: setup of redis
  hosts: redis
  become: yes

  tasks:
    - name: Ensure EPEL and Remi repositories are installed
      ansible.builtin.yum:
        name:
          - epel-release
          - https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: present

    - name: Reset existing Redis module (if any)
      ansible.builtin.shell: dnf module reset redis -y
      ignore_errors: yes

    - name: Enable Redis 6.2 stream
      ansible.builtin.shell: dnf module enable redis:remi-6.2 -y
      register: redis_enable
      changed_when: "'enabled' in redis_enable.stdout or 'Enabling module' in redis_enable.stdout"

    - name: Install Redis
      ansible.builtin.yum:
        name: redis
        state: present

    - name: Update redis listen address
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: '^bind\s+127\.0\.0\.1'
        replace: "bind 0.0.0.0"

    - name: Enable and start redis service
      ansible.builtin.systemd:
        name: redis
        state: started
        enabled: yes
