- name: setup of redis
  hosts: redis
  become: yes

  tasks:
    - name: Enable redis6 extras repository
      ansible.builtin.shell: amazon-linux-extras enable redis6 -y
      args:
        creates: /etc/yum.repos.d/amzn2-extras.repo

    - name: Install Redis
      ansible.builtin.yum:
        name: redis
        state: present

    - name: Update redis listen address
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: '^bind\s+127\.0\.0\.1'
        replace: "bind 0.0.0.0"

    - name: Enable and start redis service
      ansible.builtin.systemd:
        name: redis
        state: started
        enabled: yes
